# Generated by Django 4.2.30 on 2026-09-27 18:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("country", models.CharField(default="USA", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Dealer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dealer_id", models.IntegerField(unique=True)),
                ("full_name", models.CharField(max_length=150)),
                ("short_name", models.CharField(blank=True, default="", max_length=50)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                ("zip", models.CharField(max_length=20)),
                ("lat", models.FloatField(default=0.0)),
                ("long", models.FloatField(default=0.0)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("review", models.TextField()),
                ("purchase", models.BooleanField(default=False)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("car_make", models.CharField(blank=True, default="", max_length=100)),
                ("car_model", models.CharField(blank=True, default="", max_length=100)),
                ("car_year", models.IntegerField(blank=True, null=True)),
                ("sentiment", models.CharField(default="neutral", max_length=20)),
                (
                    "rating",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="djangoapp.dealer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SEDAN", "Sedan"),
                            ("SUV", "SUV"),
                            ("WAGON", "Wagon"),
                            ("TRUCK", "Truck"),
                            ("HATCHBACK", "Hatchback"),
                            ("COUPE", "Coupe"),
                            ("CONVERTIBLE", "Convertible"),
                        ],
                        default="SEDAN",
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        default=2023,
                        validators=[
                            django.core.validators.MinValueValidator(2010),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                    ),
                ),
                (
                    "car_make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="djangoapp.carmake",
                    ),
                ),
            ],
        ),
    ]
