apiVersion: v1
kind: Service
metadata:
  name: car-dealership-service
  labels:
    app: car-dealership
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: car-dealership
